version: '3.6'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DATABASE
      # MYSQL_USER: user
      # MYSQL_PASSWORD: user
    ports:
      - $MYSQLDB_LOCAL_PORT:$DB_PORT
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  app:
    depends_on:
     - db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
     - DB_HOST=db
     - DB_USER=$DB_USER
     - DB_PASSWORD=$DB_PASSWORD
     - DB_NAME=$DATABASE
     - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
    volumes:
     - ./:/backend


# version: '3.8'

# services:
#   mysqldb:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
#       - MYSQL_DATABASE=$DATABASE
#     ports:
#       - $MYSQLDB_LOCAL_PORT:$DB_PORT
#     volumes:
#     - ./init:/docker-entrypoint-initdb.d

# app:
#   depends_on:
#     - mysqldb
#   build: ./bezkoder-app
#   restart: unless-stopped
#   env_file: ./.env
#   ports:
#     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#   environment:
#     - DB_HOST=mysqldb
#     - DB_USER=$MYSQLDB_USER
#     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#     - DB_NAME=$MYSQLDB_DATABASE
#     - DB_PORT=$MYSQLDB_DOCKER_PORT
#   stdin_open: true
#   tty: true

# volumes: 
#   db:
